port: 7350

console:
  cors_allowed_origins:
    - "https://lila-tictactoe-eta.vercel.app"
    - "https://lila-tictactoe-sivas-projects-4552e9c8.vercel.app"

runtime:
  http_key: "defaultkey"

logger:
  level: "info"

database:
  connection_string: "sqlite:///nakama/data/nakama.db"
